TrainingArguments:
  BATCH_SIZE : 128
  EPOCHS : 60 # BEFORE 25
  LEARNING_RATE : 3e-4
  PATCH_SIZE : 4 # 4X4
  NUM_CLASSES : 10 # 10 Classes airplane , bus etc
  IMAGE_SIZE : 32
  CHANNELS : 3
  EMBED_DIM : 256
  NUM_HEADS : 8  # Number of multi head attentions
  DEPTH : 8 # before 6 TRANSFORMERS
  MLP_DIM : 768
  DROP_RATE : 0.1
  WEIGHT_DECAY : 0.01 # ADDED FOR AUG

HyperParameterTuning:
  BATCH_SIZE : 128
  EPOCHS : 60 # BEFORE 25
  LEARNING_RATE : 3e-4
  PATCH_SIZE : 4 # 4X4
  NUM_CLASSES : 10 # 10 Classes airplane , bus etc
  IMAGE_SIZE : 32
  CHANNELS : 3
  EMBED_DIM : 256
  NUM_HEADS : 8  # Number of multi head attentions
  DEPTH : 8 # before 6 TRANSFORMERS
  MLP_DIM : 768
  DROP_RATE : 0.1
  WEIGHT_DECAY : 0.01 # ADDED FOR AUG