artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  unzip_dir : artifacts/data_ingestion/unzip_file

data_validation:
  root_dir: artifacts/data_validation
  data_set_dir: artifacts/data_ingestion
  STATUS_FILE : artifacts/data_validation/status.txt

data_transformation:
  dataset_dir : artifacts/data_ingestion


model_trainer:
  root_dir : artifacts/model
  trained_model : artifacts/model/trained_model.pkl
  train_accuracy : artifacts/models/train/train_accuracy.json
  train_loss : artifacts/models/train/train_loss.json
  data_dir : artifacts/data_ingestion

model_evaluation:
  root_dir : artifacts/model_evaluation
  test_accuracy : artifacts/model_evaluation/test/test_accuracy.json
  test_loss : artifacts/model_evaluation/test/test_loss.json
  best_model : artifacts/model_evaluation/best_model.pkl
