artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  unzip_dir : artifacts/data_ingestion/unzip_file

data_validation:
  root_dir: artifacts/data_validation
  data_set_dir: artifacts/data_ingestion
  STATUS_FILE : artifacts/data_validation/status.txt

data_transformation:
  dataset_dir : artifacts/data_ingestion
