artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  train_dir : artifacts/data_ingestion/train
  test_dir : artifacts/data_ingestion/test
  unzip_dir : artifacts/data_ingestion/unzip_file